services:
  spring_app:
    image: storybubles_spring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${PRODUCTION_DB_URL}
      DB_USERNAME: ${PRODUCTION_DB_USERNAME}
      DB_PASSWORD: ${PRODUCTION_DB_PASSWORD}
    depends_on:
      - postgresql_db

  postgresql_db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PRODUCTION_DB}
      POSTGRES_USER: ${PRODUCTION_DB_USERNAME}
      POSTGRES_PASSWORD: ${PRODUCTION_DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
